config/routes.rb
Rails.application.routes.draw do
  resources :tasks, only: [:index, :show] do
    member do
      post :cambios
    end
    resources :orders, only: :create
  end
  get 'orders/create'
  resources :orders, only: :index
  root to: 'tasks#index'
  get'tasks/show'
  devise_for :users

end

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :orders
  has_many :users, through: :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :tasks, through: :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

protected

def configure_permitted_parameters
  added_attrs = [:email, :name, :photo, :password, :password_confirmation, :remember_me]
  devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
  devise_parameter_sanitizer.permit :account_update, keys: added_attrs
end

  def buscar(task)
    Order.find_by(user_id: current_user.id, task_id: task.id)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def create
  end

  def index
    @orders = current_user.orders
    @order = Order.where(completed: true).where(user_id: current_user)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
before_action :authenticate_user!
  def index
    @tasks = Task.all
  end

  def cambios
    @cambio = buscar(Task.find(params[:id]))
    if @cambio.nil?
      @order = Order.new(user: current_user)
      @order.task_id = params[:id]
      @order.completed = true
      @order.save
    else
      @cambio.completed = !@cambio.completed
      @cambio.save
    end
      redirect_to tasks_path, notice: 'Cambio realizado con exito'
  end
  def show
    @orders = Order.all
    @orders = Order.where(completed: true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def buscar(task)
    Order.find_by(user_id: current_user.id, task_id: task.id)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def buscar(task)
    Order.find_by(user_id: current_user.id, task_id: task.id)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def buscar(task)
    Order.find_by(user_id: current_user.id, task_id: task.id)
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <h3> <%= link_to "Tareas", tasks_path %> </h3>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item ">
            <a class="nav-link" href="">usuario:<%= current_user.email%></a>
          </li>
          <li class="nav-item ">
            <a class="btn btn-link" href="<%= orders_path %>">Mis Tareas:<%= current_user.orders.where(completed: true).count%>/<%=Task.count%></a>
          </li>
          <li class="nav-item ">
          <%= link_to 'Editar perfil', edit_user_registration_path, class: "btn btn-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "salir", destroy_user_session_path, method: :delete, class: "btn btn-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Ingresar", new_user_session_path, class: "btn btn-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "registrarse", new_user_registration_path, class: "btn btn-link" %>
          </li>
        <% end %>
    </ul>
  </div>
</nav>
<p></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tareas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <% if notice.present? %>
      <div class="alert alert-primary" role="alert">
        <%= notice %>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/orders/index.html.erb
  <div class="container">
      <table class="table">
        <thead>
          <tr>
            <th> <h3>Mis Tareas</h3></th>
          </tr>
        </thead>
        <p></p>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <% if order.completed == true %>
                <th> <%= order.task.name %> </th>
              <% end %>
            </tr>
          <% end %>
            <tr>
              <th> Total Tareas: <%= current_user.orders.where(completed: true).count %></th>
            </tr>
        </tbody>
      </table>
  </div>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/tasks/index.html.erb
<div class="container">
  <div class="row">
    <% @tasks.each_slice(3) do |row| %>
      <% row.each do |task| %>
        <div class="col">
          <div class="card">
            <%= image_tag task.photo, class:'card-img-top img-thumbnail' %>
            <div class="body">
              <h5> <%= task.name %> </h5>
              <% if buscar(task).nil? || buscar(task).completed == false %>
                <%= link_to "Hacer Tarea", cambios_task_path(task), style: 'margin:10px',class: 'btn btn-success', method: :post %>
              <%else %>
                <%= link_to "Cancelar Tarea", cambios_task_path(task),style: 'margin:10px',class: 'btn btn-danger', method: :post %>
              <% end %>
              <%= link_to "Detalle Tareas", tasks_show_path, style: 'margin:10px',class: 'btn btn-success',  method: :get%>
            </div>
          </div>
        </div>
      <% end %>
      <div class="w-100" style="margin-top: 20px"> </div>
    <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <table class="table">
    <h1 class="text-center">Los 5 mas responables</h1>
    <p></p>

    <thead>
      <tr>
        <th>Photo</th>
        <th>Email</th>
        <th>Nombre</th>
        <th>Tarea</th>
      </tr>
    </thead>
    <p></p>

    <tbody>
      <% if %>
        <% @orders.take(5).each_with_index do |order|  %>
        <tr>
          <% if order.completed == true  and order.task.id == order.task_id %>
          <th><%= image_tag order.user.photo, class:'img-thumbnail', style:'max-width:50px'%></th>
          <th> <%= order.user.email %> </th>
          <th> <%= order.user.name %></th>
          <th> <%= order.task.name %> </th>
         </tr>
          <% end  %>
        <% end %>
      <% end %>
      <tbody>
  </table>
  <table class="table">
    <h1 class="text-center">Todos los que ralizaron Tareas</h1>
    <p></p>

    <thead>
      <tr>
        <th>Photo</th>
        <th>Email</th>
        <th>Nombre</th>
        <th>Tarea</th>
      </tr>
    </thead>
    <p></p>
    <tbody>
      <% @orders.each_with_index do |order|  %>
        <tr>
          <% if order.completed == true %>
          <th><%= image_tag order.user.photo, class:'img-thumbnail', style:'max-width:50px'%></th>
          <th> <%= order.user.email %> </th>
          <th> <%= order.user.name %> </th>
          <th> <%= order.task.name %> </th>
         </tr>
          <% end  %>
        <% end %>
      <tbody>
  </table>
</div>